name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Setup auth-service
      run: cd auth-service && go build . && cd tests/ && go test .

    - name: Setup follow-service
      run: cd ../../follow-service && go build . && cd tests/ && go test .
    
    - name: Setup image-service
      run: cd ../../image-service && go build . && cd tests/ && go test .
    
    - name: Setup post-service
      run: cd ../../post-service && go build . && cd tests/ && go test .
    
    - name: Setup user-service
      run: cd ../../user-service && go build . && cd tests/ && go test .






