name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
  
    - name: Run auth-service tests
      env:
        POSTGRE_HOST: ${{ secrets.POSTGRE_HOST }}
        POSTGRE_PORT: ${{ secrets.POSTGRE_PORT }}
        POSTGRE_USER: ${{ secrets.POSTGRE_USER }}
        POSTGRE_PASSWORD: ${{ secrets.POSTGRE_PASSWORD }}
        POSTGRE_TEST_DB_NAME: ${{ secrets.POSTGRE_TEST_DB_NAME }}
        REDIS_TOKEN_TEST_DATABASE: ${{ secrets.REDIS_TOKEN_TEST_DATABASE }}
        REDIS_ADDRESS: ${{ secrets.REDIS_ADDRESS }}
        REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
      run: cd auth-service/tests && go test .
      

    - name: Run follow-service tests
      env:
        POSTGRE_HOST: ${{ secrets.POSTGRE_HOST }}
        POSTGRE_PORT: ${{ secrets.POSTGRE_PORT }}
        POSTGRE_USER: ${{ secrets.POSTGRE_USER }}
        POSTGRE_PASSWORD: ${{ secrets.POSTGRE_PASSWORD }}
        POSTGRE_TEST_DB_NAME: ${{ secrets.POSTGRE_TEST_DB_NAME }}
      run: cd follow-service/tests && go test .
      
    - name: Run image-service tests
      run: cd image-service/tests && go test .
    
    - name: Run post-service tests
      run: cd post-service/tests && go test .
    
    - name: Run user-service tests
      run: cd user-service/tests && go test .
